--- #YAML:1.0
name:               File-ShareDir-Install
version:            0.04
abstract:           Install shared files
author:
    - Philip Gwyn <gwyn-at-cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    ExtUtils::MakeMaker:  6.11
    File::Spec:           0
    IO::Dir:              0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
