# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         File-ShareDir-Install
version:      0.10
version_from: lib/File/ShareDir/Install.pm
installdirs:  site
requires:
    ExtUtils::MakeMaker:           6.11
    File::Spec:                    0
    IO::Dir:                       0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
